name: Upload Backups
description: Upload artifacts to my backup server

inputs:
  api_key:
    description: API key
    required: true
  project:
    description: Mod name
    required: true
  version:
    description: Mod version (without v or -MC)
    required: true
  path:
    description: File, directory or wildcard pattern that describes what to upload
    required: true

runs:
  using: composite
  steps:

  - name: Set up uv
    uses: astral-sh/setup-uv@v7
    with:
      enable-cache: true
      working-directory: ${{ github.action_path }}

  - name: Run main.py
    id: run
    env:
      WI_BACKUPS_API_KEY: ${{ inputs.api_key }}
    shell: bash
    run: |
      uv run --locked --project '${{ github.action_path }}' \
        '${{ github.action_path }}/main.py' \
        '${{ inputs.project }}' \
        '${{ inputs.version }}' \
        '${{ inputs.path }}'
